// This file was generated by Sir Bindalot, the binding generator. Ne pas toucher!

package basis

// class Core

@export
bindCore :: proc "c" (
	showAssertDialog: basis_odin_Core_showAssertDialog_cb,
	heapAlloc: basis_odin_Core_heapAlloc_cb,
	heapFree: basis_odin_Core_heapFree_cb,
	printOnHost: basis_odin_Core_printOnHost_cb,
	beginProfilingSample: basis_odin_Core_beginProfilingSample_cb,
	endProfilingSample: basis_odin_Core_endProfilingSample_cb,
	getRandomSeed: basis_odin_Core_getRandomSeed_cb,
) {
	_Core_showAssertDialog = showAssertDialog
	_Core_heapAlloc = heapAlloc
	_Core_heapFree = heapFree
	_Core_printOnHost = printOnHost
	_Core_beginProfilingSample = beginProfilingSample
	_Core_endProfilingSample = endProfilingSample
	_Core_getRandomSeed = getRandomSeed
}

// ===============================

// class App

@export
bindApp :: proc "c" (
	createApp: basis_odin_App_createApp_cb,
	getAppMode: basis_odin_App_getAppMode_cb,
	getClient: basis_odin_App_getClient_cb,
	getServer: basis_odin_App_getServer_cb,
	addInput: basis_odin_App_addInput_cb,
	getInputBufferSize: basis_odin_App_getInputBufferSize_cb,
	clearInputMappings: basis_odin_App_clearInputMappings_cb,
	mapInput: basis_odin_App_mapInput_cb,
	mapKeyboardInput: basis_odin_App_mapKeyboardInput_cb,
	mapMouseButtonInput: basis_odin_App_mapMouseButtonInput_cb,
	mapGamepadButtonInput: basis_odin_App_mapGamepadButtonInput_cb,
	registerMessage: basis_odin_App_registerMessage_cb,
	getClientGameFlowStateMachine: basis_odin_App_getClientGameFlowStateMachine_cb,
	getServerGameFlowStateMachine: basis_odin_App_getServerGameFlowStateMachine_cb,
	createAndLoadSPGame: basis_odin_App_createAndLoadSPGame_cb,
	createSPGame: basis_odin_App_createSPGame_cb,
	loadSPGame: basis_odin_App_loadSPGame_cb,
	leaveGame: basis_odin_App_leaveGame_cb,
	isLocalServerRunning: basis_odin_App_isLocalServerRunning_cb,
	isServerThreadRunning: basis_odin_App_isServerThreadRunning_cb,
	hasCommandLineParameter: basis_odin_App_hasCommandLineParameter_cb,
	getCommandLineParameter: basis_odin_App_getCommandLineParameter_cb,
	getConfigOptions: basis_odin_App_getConfigOptions_cb,
) {
	_App_createApp = createApp
	_App_getAppMode = getAppMode
	_App_getClient = getClient
	_App_getServer = getServer
	_App_addInput = addInput
	_App_getInputBufferSize = getInputBufferSize
	_App_clearInputMappings = clearInputMappings
	_App_mapInput = mapInput
	_App_mapKeyboardInput = mapKeyboardInput
	_App_mapMouseButtonInput = mapMouseButtonInput
	_App_mapGamepadButtonInput = mapGamepadButtonInput
	_App_registerMessage = registerMessage
	_App_getClientGameFlowStateMachine = getClientGameFlowStateMachine
	_App_getServerGameFlowStateMachine = getServerGameFlowStateMachine
	_App_createAndLoadSPGame = createAndLoadSPGame
	_App_createSPGame = createSPGame
	_App_loadSPGame = loadSPGame
	_App_leaveGame = leaveGame
	_App_isLocalServerRunning = isLocalServerRunning
	_App_isServerThreadRunning = isServerThreadRunning
	_App_hasCommandLineParameter = hasCommandLineParameter
	_App_getCommandLineParameter = getCommandLineParameter
	_App_getConfigOptions = getConfigOptions
}

// ===============================

// class ModController

@export
bindModController :: proc "c" (
	createModController: basis_odin_ModController_createModController_cb,
	getAppMode: basis_odin_ModController_getAppMode_cb,
	getClient: basis_odin_ModController_getClient_cb,
	getServer: basis_odin_ModController_getServer_cb,
	registerMessage: basis_odin_ModController_registerMessage_cb,
) {
	_ModController_createModController = createModController
	_ModController_getAppMode = getAppMode
	_ModController_getClient = getClient
	_ModController_getServer = getServer
	_ModController_registerMessage = registerMessage
}

// ===============================

// class Client

@export
bindClient :: proc "c" (
	getHostID: basis_odin_Client_getHostID_cb,
	getRenderer: basis_odin_Client_getRenderer_cb,
	getGameSession: basis_odin_Client_getGameSession_cb,
	getGameState: basis_odin_Client_getGameState_cb,
	getPhysicsEnginePtr: basis_odin_Client_getPhysicsEnginePtr_cb,
	getPrimaryPhysicsScene: basis_odin_Client_getPrimaryPhysicsScene_cb,
	getInterpolationFactor: basis_odin_Client_getInterpolationFactor_cb,
	createMessageNode: basis_odin_Client_createMessageNode_cb,
	addRPCListener: basis_odin_Client_addRPCListener_cb,
	removeRPCListener: basis_odin_Client_removeRPCListener_cb,
	sendNetworkMessageToHostID: basis_odin_Client_sendNetworkMessageToHostID_cb,
	sendNetworkMessageToPeer: basis_odin_Client_sendNetworkMessageToPeer_cb,
	isConnected: basis_odin_Client_isConnected_cb,
) {
	_Client_getHostID = getHostID
	_Client_getRenderer = getRenderer
	_Client_getGameSession = getGameSession
	_Client_getGameState = getGameState
	_Client_getPhysicsEnginePtr = getPhysicsEnginePtr
	_Client_getPrimaryPhysicsScene = getPrimaryPhysicsScene
	_Client_getInterpolationFactor = getInterpolationFactor
	_Client_createMessageNode = createMessageNode
	_Client_addRPCListener = addRPCListener
	_Client_removeRPCListener = removeRPCListener
	_Client_sendNetworkMessageToHostID = sendNetworkMessageToHostID
	_Client_sendNetworkMessageToPeer = sendNetworkMessageToPeer
	_Client_isConnected = isConnected
}

// ===============================

// class Server

@export
bindServer :: proc "c" (
	getGameSession: basis_odin_Server_getGameSession_cb,
	getGameState: basis_odin_Server_getGameState_cb,
	getPhysicsEnginePtr: basis_odin_Server_getPhysicsEnginePtr_cb,
	getPrimaryPhysicsScene: basis_odin_Server_getPrimaryPhysicsScene_cb,
	createMessageNode: basis_odin_Server_createMessageNode_cb,
	addRPCListener: basis_odin_Server_addRPCListener_cb,
	removeRPCListener: basis_odin_Server_removeRPCListener_cb,
	sendNetworkMessageToHostID: basis_odin_Server_sendNetworkMessageToHostID_cb,
	sendNetworkMessageToPeer: basis_odin_Server_sendNetworkMessageToPeer_cb,
	endGameSession: basis_odin_Server_endGameSession_cb,
) {
	_Server_getGameSession = getGameSession
	_Server_getGameState = getGameState
	_Server_getPhysicsEnginePtr = getPhysicsEnginePtr
	_Server_getPrimaryPhysicsScene = getPrimaryPhysicsScene
	_Server_createMessageNode = createMessageNode
	_Server_addRPCListener = addRPCListener
	_Server_removeRPCListener = removeRPCListener
	_Server_sendNetworkMessageToHostID = sendNetworkMessageToHostID
	_Server_sendNetworkMessageToPeer = sendNetworkMessageToPeer
	_Server_endGameSession = endGameSession
}

// ===============================

// class CommandPrompt

@export
bindCommandPrompt :: proc "c" (
	parseCommand: basis_odin_CommandPrompt_parseCommand_cb,
	registerIntValue: basis_odin_CommandPrompt_registerIntValue_cb,
	registerFloatValue: basis_odin_CommandPrompt_registerFloatValue_cb,
	registerBoolValue: basis_odin_CommandPrompt_registerBoolValue_cb,
	registerFunction: basis_odin_CommandPrompt_registerFunction_cb,
	unregister: basis_odin_CommandPrompt_unregister_cb,
	outputLine: basis_odin_CommandPrompt_outputLine_cb,
	outputErrorLine: basis_odin_CommandPrompt_outputErrorLine_cb,
	getIntParameter: basis_odin_CommandPrompt_getIntParameter_cb,
	getFloatParameter: basis_odin_CommandPrompt_getFloatParameter_cb,
	getBoolParameter: basis_odin_CommandPrompt_getBoolParameter_cb,
	getStringParameter: basis_odin_CommandPrompt_getStringParameter_cb,
) {
	_CommandPrompt_parseCommand = parseCommand
	_CommandPrompt_registerIntValue = registerIntValue
	_CommandPrompt_registerFloatValue = registerFloatValue
	_CommandPrompt_registerBoolValue = registerBoolValue
	_CommandPrompt_registerFunction = registerFunction
	_CommandPrompt_unregister = unregister
	_CommandPrompt_outputLine = outputLine
	_CommandPrompt_outputErrorLine = outputErrorLine
	_CommandPrompt_getIntParameter = getIntParameter
	_CommandPrompt_getFloatParameter = getFloatParameter
	_CommandPrompt_getBoolParameter = getBoolParameter
	_CommandPrompt_getStringParameter = getStringParameter
}

// ===============================

// class ConfigOptions

@export
bindConfigOptions :: proc "c" (
	addString: basis_odin_ConfigOptions_addString_cb,
	addFloat: basis_odin_ConfigOptions_addFloat_cb,
	addInteger: basis_odin_ConfigOptions_addInteger_cb,
	addBool: basis_odin_ConfigOptions_addBool_cb,
	getString: basis_odin_ConfigOptions_getString_cb,
	getFloat: basis_odin_ConfigOptions_getFloat_cb,
	getInteger: basis_odin_ConfigOptions_getInteger_cb,
	getBool: basis_odin_ConfigOptions_getBool_cb,
	setString: basis_odin_ConfigOptions_setString_cb,
	setFloat: basis_odin_ConfigOptions_setFloat_cb,
	setInteger: basis_odin_ConfigOptions_setInteger_cb,
	setBool: basis_odin_ConfigOptions_setBool_cb,
	hasString: basis_odin_ConfigOptions_hasString_cb,
	hasFloat: basis_odin_ConfigOptions_hasFloat_cb,
	hasInteger: basis_odin_ConfigOptions_hasInteger_cb,
	hasBool: basis_odin_ConfigOptions_hasBool_cb,
	save: basis_odin_ConfigOptions_save_cb,
) {
	_ConfigOptions_addString = addString
	_ConfigOptions_addFloat = addFloat
	_ConfigOptions_addInteger = addInteger
	_ConfigOptions_addBool = addBool
	_ConfigOptions_getString = getString
	_ConfigOptions_getFloat = getFloat
	_ConfigOptions_getInteger = getInteger
	_ConfigOptions_getBool = getBool
	_ConfigOptions_setString = setString
	_ConfigOptions_setFloat = setFloat
	_ConfigOptions_setInteger = setInteger
	_ConfigOptions_setBool = setBool
	_ConfigOptions_hasString = hasString
	_ConfigOptions_hasFloat = hasFloat
	_ConfigOptions_hasInteger = hasInteger
	_ConfigOptions_hasBool = hasBool
	_ConfigOptions_save = save
}

// ===============================

// class PlayerController

@export
bindPlayerController :: proc "c" (
	getClient: basis_odin_PlayerController_getClient_cb,
	getServer: basis_odin_PlayerController_getServer_cb,
	getInputRange: basis_odin_PlayerController_getInputRange_cb,
	getInputState: basis_odin_PlayerController_getInputState_cb,
	getInputAction: basis_odin_PlayerController_getInputAction_cb,
	subscribeToMessageCategory: basis_odin_PlayerController_subscribeToMessageCategory_cb,
	allocMsgParams: basis_odin_PlayerController_allocMsgParams_cb,
	sendMessage: basis_odin_PlayerController_sendMessage_cb,
) {
	_PlayerController_getClient = getClient
	_PlayerController_getServer = getServer
	_PlayerController_getInputRange = getInputRange
	_PlayerController_getInputState = getInputState
	_PlayerController_getInputAction = getInputAction
	_PlayerController_subscribeToMessageCategory = subscribeToMessageCategory
	_PlayerController_allocMsgParams = allocMsgParams
	_PlayerController_sendMessage = sendMessage
}

// ===============================

// class DebugDraw

@export
bindDebugDraw :: proc "c" (
	drawLine2D: basis_odin_DebugDraw_drawLine2D_cb,
	drawLine3D: basis_odin_DebugDraw_drawLine3D_cb,
	drawAxisCross: basis_odin_DebugDraw_drawAxisCross_cb,
	drawSphere: basis_odin_DebugDraw_drawSphere_cb,
	drawTriangle3D: basis_odin_DebugDraw_drawTriangle3D_cb,
	drawString: basis_odin_DebugDraw_drawString_cb,
	drawStringXY: basis_odin_DebugDraw_drawStringXY_cb,
) {
	_DebugDraw_drawLine2D = drawLine2D
	_DebugDraw_drawLine3D = drawLine3D
	_DebugDraw_drawAxisCross = drawAxisCross
	_DebugDraw_drawSphere = drawSphere
	_DebugDraw_drawTriangle3D = drawTriangle3D
	_DebugDraw_drawString = drawString
	_DebugDraw_drawStringXY = drawStringXY
}

// ===============================

// class GameObject

@export
bindGameObject :: proc "c" (
	getName: basis_odin_GameObject_getName_cb,
	getType: basis_odin_GameObject_getType_cb,
	getComponentPtrByShortName: basis_odin_GameObject_getComponentPtrByShortName_cb,
	getComponentPtrByTypeName: basis_odin_GameObject_getComponentPtrByTypeName_cb,
	addGameObjectMeshInstanceMapping: basis_odin_GameObject_addGameObjectMeshInstanceMapping_cb,
	removeGameObjectMeshInstanceMapping: basis_odin_GameObject_removeGameObjectMeshInstanceMapping_cb,
	getNameHash: basis_odin_GameObject_getNameHash_cb,
	getWorldTransform: basis_odin_GameObject_getWorldTransform_cb,
	setWorldTransform: basis_odin_GameObject_setWorldTransform_cb,
	getMeshComponentData: basis_odin_GameObject_getMeshComponentData_cb,
	getPhysicsActor: basis_odin_GameObject_getPhysicsActor_cb,
	setGameTag: basis_odin_GameObject_setGameTag_cb,
	getGameTag: basis_odin_GameObject_getGameTag_cb,
	getRenderSceneNode: basis_odin_GameObject_getRenderSceneNode_cb,
) {
	_GameObject_getName = getName
	_GameObject_getType = getType
	_GameObject_getComponentPtrByShortName = getComponentPtrByShortName
	_GameObject_getComponentPtrByTypeName = getComponentPtrByTypeName
	_GameObject_addGameObjectMeshInstanceMapping = addGameObjectMeshInstanceMapping
	_GameObject_removeGameObjectMeshInstanceMapping = removeGameObjectMeshInstanceMapping
	_GameObject_getNameHash = getNameHash
	_GameObject_getWorldTransform = getWorldTransform
	_GameObject_setWorldTransform = setWorldTransform
	_GameObject_getMeshComponentData = getMeshComponentData
	_GameObject_getPhysicsActor = getPhysicsActor
	_GameObject_setGameTag = setGameTag
	_GameObject_getGameTag = getGameTag
	_GameObject_getRenderSceneNode = getRenderSceneNode
}

// ===============================

// class ComponentContext

@export
bindComponentContext :: proc "c" (
	getName: basis_odin_ComponentContext_getName_cb,
	onClient: basis_odin_ComponentContext_onClient_cb,
	inEditor: basis_odin_ComponentContext_inEditor_cb,
	getClient: basis_odin_ComponentContext_getClient_cb,
	getServer: basis_odin_ComponentContext_getServer_cb,
	getGameObject: basis_odin_ComponentContext_getGameObject_cb,
	subscribeToMessageCategory: basis_odin_ComponentContext_subscribeToMessageCategory_cb,
	allocMsgParams: basis_odin_ComponentContext_allocMsgParams_cb,
	sendMessage: basis_odin_ComponentContext_sendMessage_cb,
	getPhysicsEnginePtr: basis_odin_ComponentContext_getPhysicsEnginePtr_cb,
	getPrimaryPhysicsScene: basis_odin_ComponentContext_getPrimaryPhysicsScene_cb,
	getRenderer: basis_odin_ComponentContext_getRenderer_cb,
	getGameSession: basis_odin_ComponentContext_getGameSession_cb,
	getGameState: basis_odin_ComponentContext_getGameState_cb,
	getPosition: basis_odin_ComponentContext_getPosition_cb,
	setPosition: basis_odin_ComponentContext_setPosition_cb,
	getOrientation: basis_odin_ComponentContext_getOrientation_cb,
	setOrientation: basis_odin_ComponentContext_setOrientation_cb,
	getLinearVelocity: basis_odin_ComponentContext_getLinearVelocity_cb,
	getAngularVelocity: basis_odin_ComponentContext_getAngularVelocity_cb,
	setTransform: basis_odin_ComponentContext_setTransform_cb,
	setTransformWithVelocities: basis_odin_ComponentContext_setTransformWithVelocities_cb,
	getWorldMatrix: basis_odin_ComponentContext_getWorldMatrix_cb,
	getRenderSceneNode: basis_odin_ComponentContext_getRenderSceneNode_cb,
	isClientLocalAvatar: basis_odin_ComponentContext_isClientLocalAvatar_cb,
	getAvatarHostID: basis_odin_ComponentContext_getAvatarHostID_cb,
	getInputRange: basis_odin_ComponentContext_getInputRange_cb,
	getInputState: basis_odin_ComponentContext_getInputState_cb,
	getInputAction: basis_odin_ComponentContext_getInputAction_cb,
	getCharacterController: basis_odin_ComponentContext_getCharacterController_cb,
	getPhysicsActor: basis_odin_ComponentContext_getPhysicsActor_cb,
	flushExposedProperties: basis_odin_ComponentContext_flushExposedProperties_cb,
	getParentGameObject: basis_odin_ComponentContext_getParentGameObject_cb,
	registerPipe: basis_odin_ComponentContext_registerPipe_cb,
	writeToPipe: basis_odin_ComponentContext_writeToPipe_cb,
	callScriptOnTick: basis_odin_ComponentContext_callScriptOnTick_cb,
	getScriptFunctionByDecl: basis_odin_ComponentContext_getScriptFunctionByDecl_cb,
	getScriptFunctionByASFuncPtr: basis_odin_ComponentContext_getScriptFunctionByASFuncPtr_cb,
) {
	_ComponentContext_getName = getName
	_ComponentContext_onClient = onClient
	_ComponentContext_inEditor = inEditor
	_ComponentContext_getClient = getClient
	_ComponentContext_getServer = getServer
	_ComponentContext_getGameObject = getGameObject
	_ComponentContext_subscribeToMessageCategory = subscribeToMessageCategory
	_ComponentContext_allocMsgParams = allocMsgParams
	_ComponentContext_sendMessage = sendMessage
	_ComponentContext_getPhysicsEnginePtr = getPhysicsEnginePtr
	_ComponentContext_getPrimaryPhysicsScene = getPrimaryPhysicsScene
	_ComponentContext_getRenderer = getRenderer
	_ComponentContext_getGameSession = getGameSession
	_ComponentContext_getGameState = getGameState
	_ComponentContext_getPosition = getPosition
	_ComponentContext_setPosition = setPosition
	_ComponentContext_getOrientation = getOrientation
	_ComponentContext_setOrientation = setOrientation
	_ComponentContext_getLinearVelocity = getLinearVelocity
	_ComponentContext_getAngularVelocity = getAngularVelocity
	_ComponentContext_setTransform = setTransform
	_ComponentContext_setTransformWithVelocities = setTransformWithVelocities
	_ComponentContext_getWorldMatrix = getWorldMatrix
	_ComponentContext_getRenderSceneNode = getRenderSceneNode
	_ComponentContext_isClientLocalAvatar = isClientLocalAvatar
	_ComponentContext_getAvatarHostID = getAvatarHostID
	_ComponentContext_getInputRange = getInputRange
	_ComponentContext_getInputState = getInputState
	_ComponentContext_getInputAction = getInputAction
	_ComponentContext_getCharacterController = getCharacterController
	_ComponentContext_getPhysicsActor = getPhysicsActor
	_ComponentContext_flushExposedProperties = flushExposedProperties
	_ComponentContext_getParentGameObject = getParentGameObject
	_ComponentContext_registerPipe = registerPipe
	_ComponentContext_writeToPipe = writeToPipe
	_ComponentContext_callScriptOnTick = callScriptOnTick
	_ComponentContext_getScriptFunctionByDecl = getScriptFunctionByDecl
	_ComponentContext_getScriptFunctionByASFuncPtr = getScriptFunctionByASFuncPtr
}

// ===============================

// class AngelScriptFunction

@export
bindAngelScriptFunction :: proc "c" (
	prepareCall: basis_odin_AngelScriptFunction_prepareCall_cb,
	setBoolParam: basis_odin_AngelScriptFunction_setBoolParam_cb,
	setIntParam: basis_odin_AngelScriptFunction_setIntParam_cb,
	setUintParam: basis_odin_AngelScriptFunction_setUintParam_cb,
	setFloatParam: basis_odin_AngelScriptFunction_setFloatParam_cb,
	setStringParam: basis_odin_AngelScriptFunction_setStringParam_cb,
	setGameObjectRefParam: basis_odin_AngelScriptFunction_setGameObjectRefParam_cb,
	executeCall: basis_odin_AngelScriptFunction_executeCall_cb,
) {
	_AngelScriptFunction_prepareCall = prepareCall
	_AngelScriptFunction_setBoolParam = setBoolParam
	_AngelScriptFunction_setIntParam = setIntParam
	_AngelScriptFunction_setUintParam = setUintParam
	_AngelScriptFunction_setFloatParam = setFloatParam
	_AngelScriptFunction_setStringParam = setStringParam
	_AngelScriptFunction_setGameObjectRefParam = setGameObjectRefParam
	_AngelScriptFunction_executeCall = executeCall
}

// ===============================

// class MessageParameters

@export
bindMessageParameters :: proc "c" (
	addInt: basis_odin_MessageParameters_addInt_cb,
	getInt: basis_odin_MessageParameters_getInt_cb,
	addUint: basis_odin_MessageParameters_addUint_cb,
	getUint: basis_odin_MessageParameters_getUint_cb,
	addUint64: basis_odin_MessageParameters_addUint64_cb,
	getUint64: basis_odin_MessageParameters_getUint64_cb,
	addFloat: basis_odin_MessageParameters_addFloat_cb,
	getFloat: basis_odin_MessageParameters_getFloat_cb,
	addVec3: basis_odin_MessageParameters_addVec3_cb,
	getVec3: basis_odin_MessageParameters_getVec3_cb,
	addVec4: basis_odin_MessageParameters_addVec4_cb,
	getVec4: basis_odin_MessageParameters_getVec4_cb,
	addQuaternion: basis_odin_MessageParameters_addQuaternion_cb,
	getQuaternion: basis_odin_MessageParameters_getQuaternion_cb,
	addString: basis_odin_MessageParameters_addString_cb,
	getString: basis_odin_MessageParameters_getString_cb,
) {
	_MessageParameters_addInt = addInt
	_MessageParameters_getInt = getInt
	_MessageParameters_addUint = addUint
	_MessageParameters_getUint = getUint
	_MessageParameters_addUint64 = addUint64
	_MessageParameters_getUint64 = getUint64
	_MessageParameters_addFloat = addFloat
	_MessageParameters_getFloat = getFloat
	_MessageParameters_addVec3 = addVec3
	_MessageParameters_getVec3 = getVec3
	_MessageParameters_addVec4 = addVec4
	_MessageParameters_getVec4 = getVec4
	_MessageParameters_addQuaternion = addQuaternion
	_MessageParameters_getQuaternion = getQuaternion
	_MessageParameters_addString = addString
	_MessageParameters_getString = getString
}

// ===============================

// class MessageNode

@export
bindMessageNode :: proc "c" (
	destroy: basis_odin_MessageNode_destroy_cb,
	subscribeToMessageCategory: basis_odin_MessageNode_subscribeToMessageCategory_cb,
	allocMsgParams: basis_odin_MessageNode_allocMsgParams_cb,
	sendMessage: basis_odin_MessageNode_sendMessage_cb,
) {
	_MessageNode_destroy = destroy
	_MessageNode_subscribeToMessageCategory = subscribeToMessageCategory
	_MessageNode_allocMsgParams = allocMsgParams
	_MessageNode_sendMessage = sendMessage
}

// ===============================

// class InputManager

@export
bindInputManager :: proc "c" (
	addGameInputContextToFront: basis_odin_InputManager_addGameInputContextToFront_cb,
	addGameInputContextToBack: basis_odin_InputManager_addGameInputContextToBack_cb,
	isGameInputContextEnabled: basis_odin_InputManager_isGameInputContextEnabled_cb,
	removeGameInputContext: basis_odin_InputManager_removeGameInputContext_cb,
	getNFirstEnabledInputContexts: basis_odin_InputManager_getNFirstEnabledInputContexts_cb,
	isCursorLocked: basis_odin_InputManager_isCursorLocked_cb,
	lockCursor: basis_odin_InputManager_lockCursor_cb,
	releaseCursor: basis_odin_InputManager_releaseCursor_cb,
	getGameInputMode: basis_odin_InputManager_getGameInputMode_cb,
	isKeyPressed: basis_odin_InputManager_isKeyPressed_cb,
	isMouseButtonPressed: basis_odin_InputManager_isMouseButtonPressed_cb,
	getMappedKeyCode: basis_odin_InputManager_getMappedKeyCode_cb,
	getMappedMouseButton: basis_odin_InputManager_getMappedMouseButton_cb,
	getMappedGamepadButton: basis_odin_InputManager_getMappedGamepadButton_cb,
	getMappedInputSource: basis_odin_InputManager_getMappedInputSource_cb,
) {
	_InputManager_addGameInputContextToFront = addGameInputContextToFront
	_InputManager_addGameInputContextToBack = addGameInputContextToBack
	_InputManager_isGameInputContextEnabled = isGameInputContextEnabled
	_InputManager_removeGameInputContext = removeGameInputContext
	_InputManager_getNFirstEnabledInputContexts = getNFirstEnabledInputContexts
	_InputManager_isCursorLocked = isCursorLocked
	_InputManager_lockCursor = lockCursor
	_InputManager_releaseCursor = releaseCursor
	_InputManager_getGameInputMode = getGameInputMode
	_InputManager_isKeyPressed = isKeyPressed
	_InputManager_isMouseButtonPressed = isMouseButtonPressed
	_InputManager_getMappedKeyCode = getMappedKeyCode
	_InputManager_getMappedMouseButton = getMappedMouseButton
	_InputManager_getMappedGamepadButton = getMappedGamepadButton
	_InputManager_getMappedInputSource = getMappedInputSource
}

// ===============================

// class PropagatedValue

@export
bindPropagatedValue :: proc "c" (
	createFloat: basis_odin_PropagatedValue_createFloat_cb,
	createDouble: basis_odin_PropagatedValue_createDouble_cb,
	createInt32: basis_odin_PropagatedValue_createInt32_cb,
	createUint32: basis_odin_PropagatedValue_createUint32_cb,
	createInt16: basis_odin_PropagatedValue_createInt16_cb,
	createUint16: basis_odin_PropagatedValue_createUint16_cb,
	createInt64: basis_odin_PropagatedValue_createInt64_cb,
	createUint64: basis_odin_PropagatedValue_createUint64_cb,
	createInt8: basis_odin_PropagatedValue_createInt8_cb,
	createUint8: basis_odin_PropagatedValue_createUint8_cb,
	createBool: basis_odin_PropagatedValue_createBool_cb,
	createVec2: basis_odin_PropagatedValue_createVec2_cb,
	createVec3: basis_odin_PropagatedValue_createVec3_cb,
	createVec4: basis_odin_PropagatedValue_createVec4_cb,
	createQuaternion: basis_odin_PropagatedValue_createQuaternion_cb,
	createMat43: basis_odin_PropagatedValue_createMat43_cb,
	setFloat: basis_odin_PropagatedValue_setFloat_cb,
	setDouble: basis_odin_PropagatedValue_setDouble_cb,
	setInt32: basis_odin_PropagatedValue_setInt32_cb,
	setUint32: basis_odin_PropagatedValue_setUint32_cb,
	setInt16: basis_odin_PropagatedValue_setInt16_cb,
	setUint16: basis_odin_PropagatedValue_setUint16_cb,
	setInt64: basis_odin_PropagatedValue_setInt64_cb,
	setUint64: basis_odin_PropagatedValue_setUint64_cb,
	setInt8: basis_odin_PropagatedValue_setInt8_cb,
	setUint8: basis_odin_PropagatedValue_setUint8_cb,
	setBool: basis_odin_PropagatedValue_setBool_cb,
	setVec2: basis_odin_PropagatedValue_setVec2_cb,
	setVec3: basis_odin_PropagatedValue_setVec3_cb,
	setVec4: basis_odin_PropagatedValue_setVec4_cb,
	setQuaternion: basis_odin_PropagatedValue_setQuaternion_cb,
	setMat43: basis_odin_PropagatedValue_setMat43_cb,
	createAction: basis_odin_PropagatedValue_createAction_cb,
	fireAction: basis_odin_PropagatedValue_fireAction_cb,
) {
	_PropagatedValue_createFloat = createFloat
	_PropagatedValue_createDouble = createDouble
	_PropagatedValue_createInt32 = createInt32
	_PropagatedValue_createUint32 = createUint32
	_PropagatedValue_createInt16 = createInt16
	_PropagatedValue_createUint16 = createUint16
	_PropagatedValue_createInt64 = createInt64
	_PropagatedValue_createUint64 = createUint64
	_PropagatedValue_createInt8 = createInt8
	_PropagatedValue_createUint8 = createUint8
	_PropagatedValue_createBool = createBool
	_PropagatedValue_createVec2 = createVec2
	_PropagatedValue_createVec3 = createVec3
	_PropagatedValue_createVec4 = createVec4
	_PropagatedValue_createQuaternion = createQuaternion
	_PropagatedValue_createMat43 = createMat43
	_PropagatedValue_setFloat = setFloat
	_PropagatedValue_setDouble = setDouble
	_PropagatedValue_setInt32 = setInt32
	_PropagatedValue_setUint32 = setUint32
	_PropagatedValue_setInt16 = setInt16
	_PropagatedValue_setUint16 = setUint16
	_PropagatedValue_setInt64 = setInt64
	_PropagatedValue_setUint64 = setUint64
	_PropagatedValue_setInt8 = setInt8
	_PropagatedValue_setUint8 = setUint8
	_PropagatedValue_setBool = setBool
	_PropagatedValue_setVec2 = setVec2
	_PropagatedValue_setVec3 = setVec3
	_PropagatedValue_setVec4 = setVec4
	_PropagatedValue_setQuaternion = setQuaternion
	_PropagatedValue_setMat43 = setMat43
	_PropagatedValue_createAction = createAction
	_PropagatedValue_fireAction = fireAction
}

// ===============================

// class SceneNode

@export
bindSceneNode :: proc "c" (
	newNode: basis_odin_SceneNode_newNode_cb,
	deleteNode: basis_odin_SceneNode_deleteNode_cb,
	createChildNode: basis_odin_SceneNode_createChildNode_cb,
	destroyChildNode: basis_odin_SceneNode_destroyChildNode_cb,
	detachAll: basis_odin_SceneNode_detachAll_cb,
	destroyAllChildNodes: basis_odin_SceneNode_destroyAllChildNodes_cb,
	setPosition: basis_odin_SceneNode_setPosition_cb,
	getPosition: basis_odin_SceneNode_getPosition_cb,
	setOrientation: basis_odin_SceneNode_setOrientation_cb,
	getOrientation: basis_odin_SceneNode_getOrientation_cb,
	setScale: basis_odin_SceneNode_setScale_cb,
	getScale: basis_odin_SceneNode_getScale_cb,
	translate: basis_odin_SceneNode_translate_cb,
	yaw: basis_odin_SceneNode_yaw_cb,
	pitch: basis_odin_SceneNode_pitch_cb,
	roll: basis_odin_SceneNode_roll_cb,
	lookAtSceneNode: basis_odin_SceneNode_lookAtSceneNode_cb,
	attachMeshInstance: basis_odin_SceneNode_attachMeshInstance_cb,
	detachMeshInstance: basis_odin_SceneNode_detachMeshInstance_cb,
	isMeshInstanceAttached: basis_odin_SceneNode_isMeshInstanceAttached_cb,
	attachCamera: basis_odin_SceneNode_attachCamera_cb,
	detachCamera: basis_odin_SceneNode_detachCamera_cb,
	isCameraAttached: basis_odin_SceneNode_isCameraAttached_cb,
	getLocalToParentTransform: basis_odin_SceneNode_getLocalToParentTransform_cb,
	getLocalToWorldTransform: basis_odin_SceneNode_getLocalToWorldTransform_cb,
	getLocalToAncestorTransform: basis_odin_SceneNode_getLocalToAncestorTransform_cb,
) {
	_SceneNode_newNode = newNode
	_SceneNode_deleteNode = deleteNode
	_SceneNode_createChildNode = createChildNode
	_SceneNode_destroyChildNode = destroyChildNode
	_SceneNode_detachAll = detachAll
	_SceneNode_destroyAllChildNodes = destroyAllChildNodes
	_SceneNode_setPosition = setPosition
	_SceneNode_getPosition = getPosition
	_SceneNode_setOrientation = setOrientation
	_SceneNode_getOrientation = getOrientation
	_SceneNode_setScale = setScale
	_SceneNode_getScale = getScale
	_SceneNode_translate = translate
	_SceneNode_yaw = yaw
	_SceneNode_pitch = pitch
	_SceneNode_roll = roll
	_SceneNode_lookAtSceneNode = lookAtSceneNode
	_SceneNode_attachMeshInstance = attachMeshInstance
	_SceneNode_detachMeshInstance = detachMeshInstance
	_SceneNode_isMeshInstanceAttached = isMeshInstanceAttached
	_SceneNode_attachCamera = attachCamera
	_SceneNode_detachCamera = detachCamera
	_SceneNode_isCameraAttached = isCameraAttached
	_SceneNode_getLocalToParentTransform = getLocalToParentTransform
	_SceneNode_getLocalToWorldTransform = getLocalToWorldTransform
	_SceneNode_getLocalToAncestorTransform = getLocalToAncestorTransform
}

// ===============================

// class PhysicsScene

@export
bindPhysicsScene :: proc "c" (
	addActor: basis_odin_PhysicsScene_addActor_cb,
	removeActor: basis_odin_PhysicsScene_removeActor_cb,
	addVehicleController: basis_odin_PhysicsScene_addVehicleController_cb,
	removeVehicleController: basis_odin_PhysicsScene_removeVehicleController_cb,
	addJoint: basis_odin_PhysicsScene_addJoint_cb,
	removeJoint: basis_odin_PhysicsScene_removeJoint_cb,
	applyRadialForce: basis_odin_PhysicsScene_applyRadialForce_cb,
	applyRadialImpulse: basis_odin_PhysicsScene_applyRadialImpulse_cb,
	sphereSweep: basis_odin_PhysicsScene_sphereSweep_cb,
	sphereSweepEx: basis_odin_PhysicsScene_sphereSweepEx_cb,
	getSphereOverlapping: basis_odin_PhysicsScene_getSphereOverlapping_cb,
	castRay: basis_odin_PhysicsScene_castRay_cb,
	castRayEx: basis_odin_PhysicsScene_castRayEx_cb,
	castRayWithCallback: basis_odin_PhysicsScene_castRayWithCallback_cb,
	setCollisionCallbacksEnabled: basis_odin_PhysicsScene_setCollisionCallbacksEnabled_cb,
) {
	_PhysicsScene_addActor = addActor
	_PhysicsScene_removeActor = removeActor
	_PhysicsScene_addVehicleController = addVehicleController
	_PhysicsScene_removeVehicleController = removeVehicleController
	_PhysicsScene_addJoint = addJoint
	_PhysicsScene_removeJoint = removeJoint
	_PhysicsScene_applyRadialForce = applyRadialForce
	_PhysicsScene_applyRadialImpulse = applyRadialImpulse
	_PhysicsScene_sphereSweep = sphereSweep
	_PhysicsScene_sphereSweepEx = sphereSweepEx
	_PhysicsScene_getSphereOverlapping = getSphereOverlapping
	_PhysicsScene_castRay = castRay
	_PhysicsScene_castRayEx = castRayEx
	_PhysicsScene_castRayWithCallback = castRayWithCallback
	_PhysicsScene_setCollisionCallbacksEnabled = setCollisionCallbacksEnabled
}

// ===============================

// class PhysicsMaterial

@export
bindPhysicsMaterial :: proc "c" (
	getDefaultMaterial: basis_odin_PhysicsMaterial_getDefaultMaterial_cb,
	getBaseMaterial: basis_odin_PhysicsMaterial_getBaseMaterial_cb,
	createMaterial: basis_odin_PhysicsMaterial_createMaterial_cb,
	getBasePhysicsMaterialName: basis_odin_PhysicsMaterial_getBasePhysicsMaterialName_cb,
	addRef: basis_odin_PhysicsMaterial_addRef_cb,
	release: basis_odin_PhysicsMaterial_release_cb,
) {
	_PhysicsMaterial_getDefaultMaterial = getDefaultMaterial
	_PhysicsMaterial_getBaseMaterial = getBaseMaterial
	_PhysicsMaterial_createMaterial = createMaterial
	_PhysicsMaterial_getBasePhysicsMaterialName = getBasePhysicsMaterialName
	_PhysicsMaterial_addRef = addRef
	_PhysicsMaterial_release = release
}

// ===============================

// class PhysicsShape

@export
bindPhysicsShape :: proc "c" (
	createBox: basis_odin_PhysicsShape_createBox_cb,
	createSphere: basis_odin_PhysicsShape_createSphere_cb,
	createCapsule: basis_odin_PhysicsShape_createCapsule_cb,
	createCylinder: basis_odin_PhysicsShape_createCylinder_cb,
	createCylinderX: basis_odin_PhysicsShape_createCylinderX_cb,
	createCylinderZ: basis_odin_PhysicsShape_createCylinderZ_cb,
	addRef: basis_odin_PhysicsShape_addRef_cb,
	release: basis_odin_PhysicsShape_release_cb,
) {
	_PhysicsShape_createBox = createBox
	_PhysicsShape_createSphere = createSphere
	_PhysicsShape_createCapsule = createCapsule
	_PhysicsShape_createCylinder = createCylinder
	_PhysicsShape_createCylinderX = createCylinderX
	_PhysicsShape_createCylinderZ = createCylinderZ
	_PhysicsShape_addRef = addRef
	_PhysicsShape_release = release
}

// ===============================

// class PhysicsActor

@export
bindPhysicsActor :: proc "c" (
	createRigidBodyDynamic: basis_odin_PhysicsActor_createRigidBodyDynamic_cb,
	createRigidBodyStatic: basis_odin_PhysicsActor_createRigidBodyStatic_cb,
	createBoxTrigger: basis_odin_PhysicsActor_createBoxTrigger_cb,
	createSphereTrigger: basis_odin_PhysicsActor_createSphereTrigger_cb,
	setWorldTransform: basis_odin_PhysicsActor_setWorldTransform_cb,
	getWorldTransform: basis_odin_PhysicsActor_getWorldTransform_cb,
	setKinematicTarget: basis_odin_PhysicsActor_setKinematicTarget_cb,
	setMassData: basis_odin_PhysicsActor_setMassData_cb,
	getWorldBounds: basis_odin_PhysicsActor_getWorldBounds_cb,
	associateWithGameObject: basis_odin_PhysicsActor_associateWithGameObject_cb,
	getAssociatedGameObject: basis_odin_PhysicsActor_getAssociatedGameObject_cb,
	isSleeping: basis_odin_PhysicsActor_isSleeping_cb,
	wakeUp: basis_odin_PhysicsActor_wakeUp_cb,
	putToSleep: basis_odin_PhysicsActor_putToSleep_cb,
	setLinearVelocity: basis_odin_PhysicsActor_setLinearVelocity_cb,
	getLinearVelocity: basis_odin_PhysicsActor_getLinearVelocity_cb,
	setAngularVelocity: basis_odin_PhysicsActor_setAngularVelocity_cb,
	getAngularVelocity: basis_odin_PhysicsActor_getAngularVelocity_cb,
	addForce: basis_odin_PhysicsActor_addForce_cb,
	addImpulse: basis_odin_PhysicsActor_addImpulse_cb,
	addRef: basis_odin_PhysicsActor_addRef_cb,
	release: basis_odin_PhysicsActor_release_cb,
) {
	_PhysicsActor_createRigidBodyDynamic = createRigidBodyDynamic
	_PhysicsActor_createRigidBodyStatic = createRigidBodyStatic
	_PhysicsActor_createBoxTrigger = createBoxTrigger
	_PhysicsActor_createSphereTrigger = createSphereTrigger
	_PhysicsActor_setWorldTransform = setWorldTransform
	_PhysicsActor_getWorldTransform = getWorldTransform
	_PhysicsActor_setKinematicTarget = setKinematicTarget
	_PhysicsActor_setMassData = setMassData
	_PhysicsActor_getWorldBounds = getWorldBounds
	_PhysicsActor_associateWithGameObject = associateWithGameObject
	_PhysicsActor_getAssociatedGameObject = getAssociatedGameObject
	_PhysicsActor_isSleeping = isSleeping
	_PhysicsActor_wakeUp = wakeUp
	_PhysicsActor_putToSleep = putToSleep
	_PhysicsActor_setLinearVelocity = setLinearVelocity
	_PhysicsActor_getLinearVelocity = getLinearVelocity
	_PhysicsActor_setAngularVelocity = setAngularVelocity
	_PhysicsActor_getAngularVelocity = getAngularVelocity
	_PhysicsActor_addForce = addForce
	_PhysicsActor_addImpulse = addImpulse
	_PhysicsActor_addRef = addRef
	_PhysicsActor_release = release
}

// ===============================

// class PhysicsJoint

@export
bindPhysicsJoint :: proc "c" (
	createFixedJoint: basis_odin_PhysicsJoint_createFixedJoint_cb,
	createSphericalJoint: basis_odin_PhysicsJoint_createSphericalJoint_cb,
	createDistanceJoint: basis_odin_PhysicsJoint_createDistanceJoint_cb,
	createDof6Joint: basis_odin_PhysicsJoint_createDof6Joint_cb,
	createSphericalSpringJoint: basis_odin_PhysicsJoint_createSphericalSpringJoint_cb,
	enableProjection: basis_odin_PhysicsJoint_enableProjection_cb,
	setBreakForce: basis_odin_PhysicsJoint_setBreakForce_cb,
	setDof6Motion: basis_odin_PhysicsJoint_setDof6Motion_cb,
	setDof6Drive: basis_odin_PhysicsJoint_setDof6Drive_cb,
	setDof6TwistLimit: basis_odin_PhysicsJoint_setDof6TwistLimit_cb,
	setDriveGoalPose: basis_odin_PhysicsJoint_setDriveGoalPose_cb,
	getConstraintForce: basis_odin_PhysicsJoint_getConstraintForce_cb,
	setInvMassScale0: basis_odin_PhysicsJoint_setInvMassScale0_cb,
	setInvInertiaScale0: basis_odin_PhysicsJoint_setInvInertiaScale0_cb,
	setInvMassScale1: basis_odin_PhysicsJoint_setInvMassScale1_cb,
	setInvInertiaScale1: basis_odin_PhysicsJoint_setInvInertiaScale1_cb,
	getInvMassScale0: basis_odin_PhysicsJoint_getInvMassScale0_cb,
	getInvInertiaScale0: basis_odin_PhysicsJoint_getInvInertiaScale0_cb,
	getInvMassScale1: basis_odin_PhysicsJoint_getInvMassScale1_cb,
	getInvInertiaScale1: basis_odin_PhysicsJoint_getInvInertiaScale1_cb,
	addRef: basis_odin_PhysicsJoint_addRef_cb,
	release: basis_odin_PhysicsJoint_release_cb,
) {
	_PhysicsJoint_createFixedJoint = createFixedJoint
	_PhysicsJoint_createSphericalJoint = createSphericalJoint
	_PhysicsJoint_createDistanceJoint = createDistanceJoint
	_PhysicsJoint_createDof6Joint = createDof6Joint
	_PhysicsJoint_createSphericalSpringJoint = createSphericalSpringJoint
	_PhysicsJoint_enableProjection = enableProjection
	_PhysicsJoint_setBreakForce = setBreakForce
	_PhysicsJoint_setDof6Motion = setDof6Motion
	_PhysicsJoint_setDof6Drive = setDof6Drive
	_PhysicsJoint_setDof6TwistLimit = setDof6TwistLimit
	_PhysicsJoint_setDriveGoalPose = setDriveGoalPose
	_PhysicsJoint_getConstraintForce = getConstraintForce
	_PhysicsJoint_setInvMassScale0 = setInvMassScale0
	_PhysicsJoint_setInvInertiaScale0 = setInvInertiaScale0
	_PhysicsJoint_setInvMassScale1 = setInvMassScale1
	_PhysicsJoint_setInvInertiaScale1 = setInvInertiaScale1
	_PhysicsJoint_getInvMassScale0 = getInvMassScale0
	_PhysicsJoint_getInvInertiaScale0 = getInvInertiaScale0
	_PhysicsJoint_getInvMassScale1 = getInvMassScale1
	_PhysicsJoint_getInvInertiaScale1 = getInvInertiaScale1
	_PhysicsJoint_addRef = addRef
	_PhysicsJoint_release = release
}

// ===============================

// class PhysicsTriMesh

@export
bindPhysicsTriMesh :: proc "c" (
	createTriMesh: basis_odin_PhysicsTriMesh_createTriMesh_cb,
	getTriangleCount: basis_odin_PhysicsTriMesh_getTriangleCount_cb,
	getTriangleVertices: basis_odin_PhysicsTriMesh_getTriangleVertices_cb,
	pointDistance: basis_odin_PhysicsTriMesh_pointDistance_cb,
	addRef: basis_odin_PhysicsTriMesh_addRef_cb,
	release: basis_odin_PhysicsTriMesh_release_cb,
) {
	_PhysicsTriMesh_createTriMesh = createTriMesh
	_PhysicsTriMesh_getTriangleCount = getTriangleCount
	_PhysicsTriMesh_getTriangleVertices = getTriangleVertices
	_PhysicsTriMesh_pointDistance = pointDistance
	_PhysicsTriMesh_addRef = addRef
	_PhysicsTriMesh_release = release
}

// ===============================

// class CharacterController

@export
bindCharacterController :: proc "c" (
	setMovementVector: basis_odin_CharacterController_setMovementVector_cb,
	getMovementVector: basis_odin_CharacterController_getMovementVector_cb,
	getLinearVelocity: basis_odin_CharacterController_getLinearVelocity_cb,
	addRef: basis_odin_CharacterController_addRef_cb,
	release: basis_odin_CharacterController_release_cb,
) {
	_CharacterController_setMovementVector = setMovementVector
	_CharacterController_getMovementVector = getMovementVector
	_CharacterController_getLinearVelocity = getLinearVelocity
	_CharacterController_addRef = addRef
	_CharacterController_release = release
}

// ===============================

// class VehicleController

@export
bindVehicleController :: proc "c" (
	createVehicleController: basis_odin_VehicleController_createVehicleController_cb,
	reinit: basis_odin_VehicleController_reinit_cb,
	setInputData: basis_odin_VehicleController_setInputData_cb,
	getInputData: basis_odin_VehicleController_getInputData_cb,
	startGearChange: basis_odin_VehicleController_startGearChange_cb,
	forceGearChange: basis_odin_VehicleController_forceGearChange_cb,
	freezeInputData: basis_odin_VehicleController_freezeInputData_cb,
	unfreezeInputData: basis_odin_VehicleController_unfreezeInputData_cb,
	getWheelCount: basis_odin_VehicleController_getWheelCount_cb,
	getWheelStateInfo: basis_odin_VehicleController_getWheelStateInfo_cb,
	getStateInfo: basis_odin_VehicleController_getStateInfo_cb,
	addRef: basis_odin_VehicleController_addRef_cb,
	release: basis_odin_VehicleController_release_cb,
) {
	_VehicleController_createVehicleController = createVehicleController
	_VehicleController_reinit = reinit
	_VehicleController_setInputData = setInputData
	_VehicleController_getInputData = getInputData
	_VehicleController_startGearChange = startGearChange
	_VehicleController_forceGearChange = forceGearChange
	_VehicleController_freezeInputData = freezeInputData
	_VehicleController_unfreezeInputData = unfreezeInputData
	_VehicleController_getWheelCount = getWheelCount
	_VehicleController_getWheelStateInfo = getWheelStateInfo
	_VehicleController_getStateInfo = getStateInfo
	_VehicleController_addRef = addRef
	_VehicleController_release = release
}

// ===============================

// class ResourceManager

@export
bindResourceManager :: proc "c" (
	init: basis_odin_ResourceManager_init_cb,
	deinit: basis_odin_ResourceManager_deinit_cb,
	acquireResource: basis_odin_ResourceManager_acquireResource_cb,
	lock: basis_odin_ResourceManager_lock_cb,
	unlock: basis_odin_ResourceManager_unlock_cb,
	registerResourceReloadedCallback: basis_odin_ResourceManager_registerResourceReloadedCallback_cb,
	unregisterResourceReloadedCallback: basis_odin_ResourceManager_unregisterResourceReloadedCallback_cb,
	beginGetResourcesWithFileExtension: basis_odin_ResourceManager_beginGetResourcesWithFileExtension_cb,
	endGetResourcesWithFileExtension: basis_odin_ResourceManager_endGetResourcesWithFileExtension_cb,
	addLooseFileResourcePack: basis_odin_ResourceManager_addLooseFileResourcePack_cb,
) {
	_ResourceManager_init = init
	_ResourceManager_deinit = deinit
	_ResourceManager_acquireResource = acquireResource
	_ResourceManager_lock = lock
	_ResourceManager_unlock = unlock
	_ResourceManager_registerResourceReloadedCallback = registerResourceReloadedCallback
	_ResourceManager_unregisterResourceReloadedCallback = unregisterResourceReloadedCallback
	_ResourceManager_beginGetResourcesWithFileExtension = beginGetResourcesWithFileExtension
	_ResourceManager_endGetResourcesWithFileExtension = endGetResourcesWithFileExtension
	_ResourceManager_addLooseFileResourcePack = addLooseFileResourcePack
}

// ===============================

// class Resource

@export
bindResource :: proc "c" (
	getSharedMesh: basis_odin_Resource_getSharedMesh_cb,
	hasPhysicsMesh: basis_odin_Resource_hasPhysicsMesh_cb,
	getPhysicsMeshData: basis_odin_Resource_getPhysicsMeshData_cb,
	getSharedMaterial: basis_odin_Resource_getSharedMaterial_cb,
	getRawData: basis_odin_Resource_getRawData_cb,
	addRef: basis_odin_Resource_addRef_cb,
	release: basis_odin_Resource_release_cb,
) {
	_Resource_getSharedMesh = getSharedMesh
	_Resource_hasPhysicsMesh = hasPhysicsMesh
	_Resource_getPhysicsMeshData = getPhysicsMeshData
	_Resource_getSharedMaterial = getSharedMaterial
	_Resource_getRawData = getRawData
	_Resource_addRef = addRef
	_Resource_release = release
}

// ===============================

// class Renderer

@export
bindRenderer :: proc "c" (
	getPrimaryScene: basis_odin_Renderer_getPrimaryScene_cb,
	addCameraToBackOfQueue: basis_odin_Renderer_addCameraToBackOfQueue_cb,
	addCameraToFrontOfQueue: basis_odin_Renderer_addCameraToFrontOfQueue_cb,
	removeCameraFromQueue: basis_odin_Renderer_removeCameraFromQueue_cb,
	getMainCamera: basis_odin_Renderer_getMainCamera_cb,
	getScreenWidth: basis_odin_Renderer_getScreenWidth_cb,
	getScreenHeight: basis_odin_Renderer_getScreenHeight_cb,
	setVignetteEnabled: basis_odin_Renderer_setVignetteEnabled_cb,
	createMesh: basis_odin_Renderer_createMesh_cb,
	createMeshManual: basis_odin_Renderer_createMeshManual_cb,
	captureSinglePre2DFrame: basis_odin_Renderer_captureSinglePre2DFrame_cb,
	captureSingleFullEndUserFrame: basis_odin_Renderer_captureSingleFullEndUserFrame_cb,
	captureSingleFullFrame: basis_odin_Renderer_captureSingleFullFrame_cb,
	startCapturingPre2DFrames: basis_odin_Renderer_startCapturingPre2DFrames_cb,
	startCapturingFullEndUserFrames: basis_odin_Renderer_startCapturingFullEndUserFrames_cb,
	startCapturingFullFrames: basis_odin_Renderer_startCapturingFullFrames_cb,
	stopCapturingFrames: basis_odin_Renderer_stopCapturingFrames_cb,
	applyDisplayOptions: basis_odin_Renderer_applyDisplayOptions_cb,
	applyVsyncAndFramerateLimit: basis_odin_Renderer_applyVsyncAndFramerateLimit_cb,
	getDisplacementEffectRenderer: basis_odin_Renderer_getDisplacementEffectRenderer_cb,
) {
	_Renderer_getPrimaryScene = getPrimaryScene
	_Renderer_addCameraToBackOfQueue = addCameraToBackOfQueue
	_Renderer_addCameraToFrontOfQueue = addCameraToFrontOfQueue
	_Renderer_removeCameraFromQueue = removeCameraFromQueue
	_Renderer_getMainCamera = getMainCamera
	_Renderer_getScreenWidth = getScreenWidth
	_Renderer_getScreenHeight = getScreenHeight
	_Renderer_setVignetteEnabled = setVignetteEnabled
	_Renderer_createMesh = createMesh
	_Renderer_createMeshManual = createMeshManual
	_Renderer_captureSinglePre2DFrame = captureSinglePre2DFrame
	_Renderer_captureSingleFullEndUserFrame = captureSingleFullEndUserFrame
	_Renderer_captureSingleFullFrame = captureSingleFullFrame
	_Renderer_startCapturingPre2DFrames = startCapturingPre2DFrames
	_Renderer_startCapturingFullEndUserFrames = startCapturingFullEndUserFrames
	_Renderer_startCapturingFullFrames = startCapturingFullFrames
	_Renderer_stopCapturingFrames = stopCapturingFrames
	_Renderer_applyDisplayOptions = applyDisplayOptions
	_Renderer_applyVsyncAndFramerateLimit = applyVsyncAndFramerateLimit
	_Renderer_getDisplacementEffectRenderer = getDisplacementEffectRenderer
}

// ===============================

// class RenderScene

@export
bindRenderScene :: proc "c" (
	getRootSceneNode: basis_odin_RenderScene_getRootSceneNode_cb,
	destroySceneNode: basis_odin_RenderScene_destroySceneNode_cb,
	createCamera: basis_odin_RenderScene_createCamera_cb,
	destroyCamera: basis_odin_RenderScene_destroyCamera_cb,
	createDynamicMeshInstance: basis_odin_RenderScene_createDynamicMeshInstance_cb,
	createStaticMeshInstance: basis_odin_RenderScene_createStaticMeshInstance_cb,
	destroyMeshInstance: basis_odin_RenderScene_destroyMeshInstance_cb,
	castRay: basis_odin_RenderScene_castRay_cb,
	getTireTrackRenderer: basis_odin_RenderScene_getTireTrackRenderer_cb,
) {
	_RenderScene_getRootSceneNode = getRootSceneNode
	_RenderScene_destroySceneNode = destroySceneNode
	_RenderScene_createCamera = createCamera
	_RenderScene_destroyCamera = destroyCamera
	_RenderScene_createDynamicMeshInstance = createDynamicMeshInstance
	_RenderScene_createStaticMeshInstance = createStaticMeshInstance
	_RenderScene_destroyMeshInstance = destroyMeshInstance
	_RenderScene_castRay = castRay
	_RenderScene_getTireTrackRenderer = getTireTrackRenderer
}

// ===============================

// class TireTrackRenderer

@export
bindTireTrackRenderer :: proc "c" (
	clear: basis_odin_TireTrackRenderer_clear_cb,
	registerTire: basis_odin_TireTrackRenderer_registerTire_cb,
	unregisterTire: basis_odin_TireTrackRenderer_unregisterTire_cb,
	beginTireTrack: basis_odin_TireTrackRenderer_beginTireTrack_cb,
	endTireTrack: basis_odin_TireTrackRenderer_endTireTrack_cb,
	updateTireTrack: basis_odin_TireTrackRenderer_updateTireTrack_cb,
	beginStaticTireTrack: basis_odin_TireTrackRenderer_beginStaticTireTrack_cb,
	addPointToStaticTireTrack: basis_odin_TireTrackRenderer_addPointToStaticTireTrack_cb,
	endStaticTireTrack: basis_odin_TireTrackRenderer_endStaticTireTrack_cb,
	removeStaticTireTrack: basis_odin_TireTrackRenderer_removeStaticTireTrack_cb,
) {
	_TireTrackRenderer_clear = clear
	_TireTrackRenderer_registerTire = registerTire
	_TireTrackRenderer_unregisterTire = unregisterTire
	_TireTrackRenderer_beginTireTrack = beginTireTrack
	_TireTrackRenderer_endTireTrack = endTireTrack
	_TireTrackRenderer_updateTireTrack = updateTireTrack
	_TireTrackRenderer_beginStaticTireTrack = beginStaticTireTrack
	_TireTrackRenderer_addPointToStaticTireTrack = addPointToStaticTireTrack
	_TireTrackRenderer_endStaticTireTrack = endStaticTireTrack
	_TireTrackRenderer_removeStaticTireTrack = removeStaticTireTrack
}

// ===============================

// class MeshGeometry

@export
bindMeshGeometry :: proc "c" (
	newGeometry: basis_odin_MeshGeometry_newGeometry_cb,
	deleteGeometry: basis_odin_MeshGeometry_deleteGeometry_cb,
	clear: basis_odin_MeshGeometry_clear_cb,
	addLodLevel: basis_odin_MeshGeometry_addLodLevel_cb,
	getLodLevel: basis_odin_MeshGeometry_getLodLevel_cb,
	getLodLevelCount: basis_odin_MeshGeometry_getLodLevelCount_cb,
) {
	_MeshGeometry_newGeometry = newGeometry
	_MeshGeometry_deleteGeometry = deleteGeometry
	_MeshGeometry_clear = clear
	_MeshGeometry_addLodLevel = addLodLevel
	_MeshGeometry_getLodLevel = getLodLevel
	_MeshGeometry_getLodLevelCount = getLodLevelCount
}

// ===============================

// class MeshGeometryLodLevel

@export
bindMeshGeometryLodLevel :: proc "c" (
	clear: basis_odin_MeshGeometryLodLevel_clear_cb,
	addSubMesh: basis_odin_MeshGeometryLodLevel_addSubMesh_cb,
	getSubMesh: basis_odin_MeshGeometryLodLevel_getSubMesh_cb,
	getSubMeshCount: basis_odin_MeshGeometryLodLevel_getSubMeshCount_cb,
) {
	_MeshGeometryLodLevel_clear = clear
	_MeshGeometryLodLevel_addSubMesh = addSubMesh
	_MeshGeometryLodLevel_getSubMesh = getSubMesh
	_MeshGeometryLodLevel_getSubMeshCount = getSubMeshCount
}

// ===============================

// class MeshGeometrySubMesh

@export
bindMeshGeometrySubMesh :: proc "c" (
	clear: basis_odin_MeshGeometrySubMesh_clear_cb,
	addIndex: basis_odin_MeshGeometrySubMesh_addIndex_cb,
	addFace: basis_odin_MeshGeometrySubMesh_addFace_cb,
	addVertex: basis_odin_MeshGeometrySubMesh_addVertex_cb,
	getVertexFormatType: basis_odin_MeshGeometrySubMesh_getVertexFormatType_cb,
	getVertexCount: basis_odin_MeshGeometrySubMesh_getVertexCount_cb,
	getIndexCount: basis_odin_MeshGeometrySubMesh_getIndexCount_cb,
) {
	_MeshGeometrySubMesh_clear = clear
	_MeshGeometrySubMesh_addIndex = addIndex
	_MeshGeometrySubMesh_addFace = addFace
	_MeshGeometrySubMesh_addVertex = addVertex
	_MeshGeometrySubMesh_getVertexFormatType = getVertexFormatType
	_MeshGeometrySubMesh_getVertexCount = getVertexCount
	_MeshGeometrySubMesh_getIndexCount = getIndexCount
}

// ===============================

// class Mesh

@export
bindMesh :: proc "c" (
	getLodLevelCount: basis_odin_Mesh_getLodLevelCount_cb,
	getLodLevel: basis_odin_Mesh_getLodLevel_cb,
	addRef: basis_odin_Mesh_addRef_cb,
	release: basis_odin_Mesh_release_cb,
) {
	_Mesh_getLodLevelCount = getLodLevelCount
	_Mesh_getLodLevel = getLodLevel
	_Mesh_addRef = addRef
	_Mesh_release = release
}

// ===============================

// class MeshLodLevel

@export
bindMeshLodLevel :: proc "c" (
	getSubMeshCount: basis_odin_MeshLodLevel_getSubMeshCount_cb,
	setSubMeshCount: basis_odin_MeshLodLevel_setSubMeshCount_cb,
	getSubMesh: basis_odin_MeshLodLevel_getSubMesh_cb,
	getBounds: basis_odin_MeshLodLevel_getBounds_cb,
	setBounds: basis_odin_MeshLodLevel_setBounds_cb,
) {
	_MeshLodLevel_getSubMeshCount = getSubMeshCount
	_MeshLodLevel_setSubMeshCount = setSubMeshCount
	_MeshLodLevel_getSubMesh = getSubMesh
	_MeshLodLevel_getBounds = getBounds
	_MeshLodLevel_setBounds = setBounds
}

// ===============================

// class MeshSubMesh

@export
bindMeshSubMesh :: proc "c" (
	getVertexFormatType: basis_odin_MeshSubMesh_getVertexFormatType_cb,
	getVertexCount: basis_odin_MeshSubMesh_getVertexCount_cb,
	setVertexCount: basis_odin_MeshSubMesh_setVertexCount_cb,
	getIndexCount: basis_odin_MeshSubMesh_getIndexCount_cb,
	setIndexCount: basis_odin_MeshSubMesh_setIndexCount_cb,
	getVertices: basis_odin_MeshSubMesh_getVertices_cb,
	getIndices: basis_odin_MeshSubMesh_getIndices_cb,
) {
	_MeshSubMesh_getVertexFormatType = getVertexFormatType
	_MeshSubMesh_getVertexCount = getVertexCount
	_MeshSubMesh_setVertexCount = setVertexCount
	_MeshSubMesh_getIndexCount = getIndexCount
	_MeshSubMesh_setIndexCount = setIndexCount
	_MeshSubMesh_getVertices = getVertices
	_MeshSubMesh_getIndices = getIndices
}

// ===============================

// class Material

@export
bindMaterial :: proc "c" (
	addRef: basis_odin_Material_addRef_cb,
	release: basis_odin_Material_release_cb,
) {
	_Material_addRef = addRef
	_Material_release = release
}

// ===============================

// class MeshInstance

@export
bindMeshInstance :: proc "c" (
	setVisible: basis_odin_MeshInstance_setVisible_cb,
	isVisible: basis_odin_MeshInstance_isVisible_cb,
	getMaterial: basis_odin_MeshInstance_getMaterial_cb,
	setMaterial: basis_odin_MeshInstance_setMaterial_cb,
	getFlags: basis_odin_MeshInstance_getFlags_cb,
	isFlagSet: basis_odin_MeshInstance_isFlagSet_cb,
	setFlagValue: basis_odin_MeshInstance_setFlagValue_cb,
	updateLightProbeData: basis_odin_MeshInstance_updateLightProbeData_cb,
	getParentSceneNode: basis_odin_MeshInstance_getParentSceneNode_cb,
) {
	_MeshInstance_setVisible = setVisible
	_MeshInstance_isVisible = isVisible
	_MeshInstance_getMaterial = getMaterial
	_MeshInstance_setMaterial = setMaterial
	_MeshInstance_getFlags = getFlags
	_MeshInstance_isFlagSet = isFlagSet
	_MeshInstance_setFlagValue = setFlagValue
	_MeshInstance_updateLightProbeData = updateLightProbeData
	_MeshInstance_getParentSceneNode = getParentSceneNode
}

// ===============================

// class Camera

@export
bindCamera :: proc "c" (
	setPerspective: basis_odin_Camera_setPerspective_cb,
	setOrthographic: basis_odin_Camera_setOrthographic_cb,
	getWorldPosition: basis_odin_Camera_getWorldPosition_cb,
	getForwardDirection: basis_odin_Camera_getForwardDirection_cb,
	getFovY: basis_odin_Camera_getFovY_cb,
	getFovX: basis_odin_Camera_getFovX_cb,
	getNearClip: basis_odin_Camera_getNearClip_cb,
	getFarClip: basis_odin_Camera_getFarClip_cb,
	getPickRay: basis_odin_Camera_getPickRay_cb,
	worldToScreen: basis_odin_Camera_worldToScreen_cb,
	worldToScreenUnbounded: basis_odin_Camera_worldToScreenUnbounded_cb,
	getViewMatrix: basis_odin_Camera_getViewMatrix_cb,
	getProjectionMatrix: basis_odin_Camera_getProjectionMatrix_cb,
	getParentSceneNode: basis_odin_Camera_getParentSceneNode_cb,
) {
	_Camera_setPerspective = setPerspective
	_Camera_setOrthographic = setOrthographic
	_Camera_getWorldPosition = getWorldPosition
	_Camera_getForwardDirection = getForwardDirection
	_Camera_getFovY = getFovY
	_Camera_getFovX = getFovX
	_Camera_getNearClip = getNearClip
	_Camera_getFarClip = getFarClip
	_Camera_getPickRay = getPickRay
	_Camera_worldToScreen = worldToScreen
	_Camera_worldToScreenUnbounded = worldToScreenUnbounded
	_Camera_getViewMatrix = getViewMatrix
	_Camera_getProjectionMatrix = getProjectionMatrix
	_Camera_getParentSceneNode = getParentSceneNode
}

// ===============================

// class DisplacementEffectRenderer

@export
bindDisplacementEffectRenderer :: proc "c" (
	createShockwaveEffect: basis_odin_DisplacementEffectRenderer_createShockwaveEffect_cb,
	createForceFieldEffect: basis_odin_DisplacementEffectRenderer_createForceFieldEffect_cb,
	createGravityCraneEffect: basis_odin_DisplacementEffectRenderer_createGravityCraneEffect_cb,
	setEffectCutoffDistance: basis_odin_DisplacementEffectRenderer_setEffectCutoffDistance_cb,
	setEffectPosition: basis_odin_DisplacementEffectRenderer_setEffectPosition_cb,
	setEffectStrength: basis_odin_DisplacementEffectRenderer_setEffectStrength_cb,
	stopEffect: basis_odin_DisplacementEffectRenderer_stopEffect_cb,
	killEffect: basis_odin_DisplacementEffectRenderer_killEffect_cb,
	killAllEffects: basis_odin_DisplacementEffectRenderer_killAllEffects_cb,
) {
	_DisplacementEffectRenderer_createShockwaveEffect = createShockwaveEffect
	_DisplacementEffectRenderer_createForceFieldEffect = createForceFieldEffect
	_DisplacementEffectRenderer_createGravityCraneEffect = createGravityCraneEffect
	_DisplacementEffectRenderer_setEffectCutoffDistance = setEffectCutoffDistance
	_DisplacementEffectRenderer_setEffectPosition = setEffectPosition
	_DisplacementEffectRenderer_setEffectStrength = setEffectStrength
	_DisplacementEffectRenderer_stopEffect = stopEffect
	_DisplacementEffectRenderer_killEffect = killEffect
	_DisplacementEffectRenderer_killAllEffects = killAllEffects
}

// ===============================

// class GameSession

@export
bindGameSession :: proc "c" (
	getSessionType: basis_odin_GameSession_getSessionType_cb,
	getClientCount: basis_odin_GameSession_getClientCount_cb,
	getClient: basis_odin_GameSession_getClient_cb,
	isPaused: basis_odin_GameSession_isPaused_cb,
	requestPause: basis_odin_GameSession_requestPause_cb,
	getLevelData: basis_odin_GameSession_getLevelData_cb,
	isContinuousSession: basis_odin_GameSession_isContinuousSession_cb,
) {
	_GameSession_getSessionType = getSessionType
	_GameSession_getClientCount = getClientCount
	_GameSession_getClient = getClient
	_GameSession_isPaused = isPaused
	_GameSession_requestPause = requestPause
	_GameSession_getLevelData = getLevelData
	_GameSession_isContinuousSession = isContinuousSession
}

// ===============================

// class GameState

@export
bindGameState :: proc "c" (
	getGameObject: basis_odin_GameState_getGameObject_cb,
	getGameObjectFromRenderable: basis_odin_GameState_getGameObjectFromRenderable_cb,
	createGameObject: basis_odin_GameState_createGameObject_cb,
	createGameObjectWithStartTransform: basis_odin_GameState_createGameObjectWithStartTransform_cb,
	createGameObjectWithSpawnPointIndex: basis_odin_GameState_createGameObjectWithSpawnPointIndex_cb,
	createGameObjectWithSpawnPointName: basis_odin_GameState_createGameObjectWithSpawnPointName_cb,
	createGameObjectWithParameters: basis_odin_GameState_createGameObjectWithParameters_cb,
	destroyGameObject: basis_odin_GameState_destroyGameObject_cb,
	hasGameObject: basis_odin_GameState_hasGameObject_cb,
	setAvatarObject: basis_odin_GameState_setAvatarObject_cb,
	clearAvatarObject: basis_odin_GameState_clearAvatarObject_cb,
	getAvatarObjectByHostID: basis_odin_GameState_getAvatarObjectByHostID_cb,
	getHostIDByAvatarObject: basis_odin_GameState_getHostIDByAvatarObject_cb,
	broadcastScriptMessage: basis_odin_GameState_broadcastScriptMessage_cb,
	generateGameObjectName: basis_odin_GameState_generateGameObjectName_cb,
) {
	_GameState_getGameObject = getGameObject
	_GameState_getGameObjectFromRenderable = getGameObjectFromRenderable
	_GameState_createGameObject = createGameObject
	_GameState_createGameObjectWithStartTransform = createGameObjectWithStartTransform
	_GameState_createGameObjectWithSpawnPointIndex = createGameObjectWithSpawnPointIndex
	_GameState_createGameObjectWithSpawnPointName = createGameObjectWithSpawnPointName
	_GameState_createGameObjectWithParameters = createGameObjectWithParameters
	_GameState_destroyGameObject = destroyGameObject
	_GameState_hasGameObject = hasGameObject
	_GameState_setAvatarObject = setAvatarObject
	_GameState_clearAvatarObject = clearAvatarObject
	_GameState_getAvatarObjectByHostID = getAvatarObjectByHostID
	_GameState_getHostIDByAvatarObject = getHostIDByAvatarObject
	_GameState_broadcastScriptMessage = broadcastScriptMessage
	_GameState_generateGameObjectName = generateGameObjectName
}

// ===============================

// class LevelData

@export
bindLevelData :: proc "c" (
	getDataBlockManager: basis_odin_LevelData_getDataBlockManager_cb,
) {
	_LevelData_getDataBlockManager = getDataBlockManager
}

// ===============================

// class LevelDataBlockManager

@export
bindLevelDataBlockManager :: proc "c" (
	getDataBlock: basis_odin_LevelDataBlockManager_getDataBlock_cb,
	addDataBlock: basis_odin_LevelDataBlockManager_addDataBlock_cb,
	addDataBlockIfDoesNotExist: basis_odin_LevelDataBlockManager_addDataBlockIfDoesNotExist_cb,
	getMutableDataBlock: basis_odin_LevelDataBlockManager_getMutableDataBlock_cb,
	hasDataBlock: basis_odin_LevelDataBlockManager_hasDataBlock_cb,
) {
	_LevelDataBlockManager_getDataBlock = getDataBlock
	_LevelDataBlockManager_addDataBlock = addDataBlock
	_LevelDataBlockManager_addDataBlockIfDoesNotExist = addDataBlockIfDoesNotExist
	_LevelDataBlockManager_getMutableDataBlock = getMutableDataBlock
	_LevelDataBlockManager_hasDataBlock = hasDataBlock
}

// ===============================

// class LevelDataBlock

@export
bindLevelDataBlock :: proc "c" (
	getReadBuffer: basis_odin_LevelDataBlock_getReadBuffer_cb,
	getChunkStartReadBufferPosition: basis_odin_LevelDataBlock_getChunkStartReadBufferPosition_cb,
	setReadBufferPosition: basis_odin_LevelDataBlock_setReadBufferPosition_cb,
	getWriteBuffer: basis_odin_LevelDataBlock_getWriteBuffer_cb,
	beginWritingChunk: basis_odin_LevelDataBlock_beginWritingChunk_cb,
	finishWritingChunk: basis_odin_LevelDataBlock_finishWritingChunk_cb,
	getChunkCount: basis_odin_LevelDataBlock_getChunkCount_cb,
) {
	_LevelDataBlock_getReadBuffer = getReadBuffer
	_LevelDataBlock_getChunkStartReadBufferPosition = getChunkStartReadBufferPosition
	_LevelDataBlock_setReadBufferPosition = setReadBufferPosition
	_LevelDataBlock_getWriteBuffer = getWriteBuffer
	_LevelDataBlock_beginWritingChunk = beginWritingChunk
	_LevelDataBlock_finishWritingChunk = finishWritingChunk
	_LevelDataBlock_getChunkCount = getChunkCount
}

// ===============================

// class NavMeshRuntime

@export
bindNavMeshRuntime :: proc "c" (
	hasNavMesh: basis_odin_NavMeshRuntime_hasNavMesh_cb,
	findPath: basis_odin_NavMeshRuntime_findPath_cb,
	findClosestPointOnNavMesh: basis_odin_NavMeshRuntime_findClosestPointOnNavMesh_cb,
	findRandomPointAroundCircle: basis_odin_NavMeshRuntime_findRandomPointAroundCircle_cb,
	overlapsNavMesh: basis_odin_NavMeshRuntime_overlapsNavMesh_cb,
	addObstacle: basis_odin_NavMeshRuntime_addObstacle_cb,
	updateObstacle: basis_odin_NavMeshRuntime_updateObstacle_cb,
	removeObstacle: basis_odin_NavMeshRuntime_removeObstacle_cb,
) {
	_NavMeshRuntime_hasNavMesh = hasNavMesh
	_NavMeshRuntime_findPath = findPath
	_NavMeshRuntime_findClosestPointOnNavMesh = findClosestPointOnNavMesh
	_NavMeshRuntime_findRandomPointAroundCircle = findRandomPointAroundCircle
	_NavMeshRuntime_overlapsNavMesh = overlapsNavMesh
	_NavMeshRuntime_addObstacle = addObstacle
	_NavMeshRuntime_updateObstacle = updateObstacle
	_NavMeshRuntime_removeObstacle = removeObstacle
}

// ===============================

// class StreamingUtils

@export
bindStreamingUtils :: proc "c" (
	setStreamingPosition: basis_odin_StreamingUtils_setStreamingPosition_cb,
	getStreamingPosition: basis_odin_StreamingUtils_getStreamingPosition_cb,
	setStreamingPositionUpdateMode: basis_odin_StreamingUtils_setStreamingPositionUpdateMode_cb,
	getStreamingPositionUpdateMode: basis_odin_StreamingUtils_getStreamingPositionUpdateMode_cb,
) {
	_StreamingUtils_setStreamingPosition = setStreamingPosition
	_StreamingUtils_getStreamingPosition = getStreamingPosition
	_StreamingUtils_setStreamingPositionUpdateMode = setStreamingPositionUpdateMode
	_StreamingUtils_getStreamingPositionUpdateMode = getStreamingPositionUpdateMode
}

// ===============================

// class ScreenFade

@export
bindScreenFade :: proc "c" (
	isActive: basis_odin_ScreenFade_isActive_cb,
	fade: basis_odin_ScreenFade_fade_cb,
	fadeWithCallback: basis_odin_ScreenFade_fadeWithCallback_cb,
	setColor: basis_odin_ScreenFade_setColor_cb,
	clear: basis_odin_ScreenFade_clear_cb,
) {
	_ScreenFade_isActive = isActive
	_ScreenFade_fade = fade
	_ScreenFade_fadeWithCallback = fadeWithCallback
	_ScreenFade_setColor = setColor
	_ScreenFade_clear = clear
}

// ===============================

// class StateMachine

@export
bindStateMachine :: proc "c" (
	registerFlowState: basis_odin_StateMachine_registerFlowState_cb,
	setCallbacksForGroup: basis_odin_StateMachine_setCallbacksForGroup_cb,
	clearCallbacksForGroup: basis_odin_StateMachine_clearCallbacksForGroup_cb,
) {
	_StateMachine_registerFlowState = registerFlowState
	_StateMachine_setCallbacksForGroup = setCallbacksForGroup
	_StateMachine_clearCallbacksForGroup = clearCallbacksForGroup
}

// ===============================

// class FlowState

@export
bindFlowState :: proc "c" (
	startTransition: basis_odin_FlowState_startTransition_cb,
	subscribeToMessageCategory: basis_odin_FlowState_subscribeToMessageCategory_cb,
	allocMsgParams: basis_odin_FlowState_allocMsgParams_cb,
	sendMessage: basis_odin_FlowState_sendMessage_cb,
	getClient: basis_odin_FlowState_getClient_cb,
	getServer: basis_odin_FlowState_getServer_cb,
) {
	_FlowState_startTransition = startTransition
	_FlowState_subscribeToMessageCategory = subscribeToMessageCategory
	_FlowState_allocMsgParams = allocMsgParams
	_FlowState_sendMessage = sendMessage
	_FlowState_getClient = getClient
	_FlowState_getServer = getServer
}

// ===============================

// class DebugOverlay

@export
bindDebugOverlay :: proc "c" (
	isVisible: basis_odin_DebugOverlay_isVisible_cb,
	setImGuiMenuBarCallbackEnabled: basis_odin_DebugOverlay_setImGuiMenuBarCallbackEnabled_cb,
	setImGuiCallbackEnabled: basis_odin_DebugOverlay_setImGuiCallbackEnabled_cb,
	debugTrace: basis_odin_DebugOverlay_debugTrace_cb,
	debugWarning: basis_odin_DebugOverlay_debugWarning_cb,
	areDebugObjectWindowKeysPressed: basis_odin_DebugOverlay_areDebugObjectWindowKeysPressed_cb,
	showDebugActionAtPosition: basis_odin_DebugOverlay_showDebugActionAtPosition_cb,
	addDebugSpawnableObjectType: basis_odin_DebugOverlay_addDebugSpawnableObjectType_cb,
) {
	_DebugOverlay_isVisible = isVisible
	_DebugOverlay_setImGuiMenuBarCallbackEnabled = setImGuiMenuBarCallbackEnabled
	_DebugOverlay_setImGuiCallbackEnabled = setImGuiCallbackEnabled
	_DebugOverlay_debugTrace = debugTrace
	_DebugOverlay_debugWarning = debugWarning
	_DebugOverlay_areDebugObjectWindowKeysPressed = areDebugObjectWindowKeysPressed
	_DebugOverlay_showDebugActionAtPosition = showDebugActionAtPosition
	_DebugOverlay_addDebugSpawnableObjectType = addDebugSpawnableObjectType
}

// ===============================

// class Editor

@export
bindEditor :: proc "c" (
	printInfo: basis_odin_Editor_printInfo_cb,
	printWarning: basis_odin_Editor_printWarning_cb,
	printError: basis_odin_Editor_printError_cb,
	getEditorCamera: basis_odin_Editor_getEditorCamera_cb,
) {
	_Editor_printInfo = printInfo
	_Editor_printWarning = printWarning
	_Editor_printError = printError
	_Editor_getEditorCamera = getEditorCamera
}

// ===============================

// class ImGui

@export
bindImGui :: proc "c" (
	begin: basis_odin_ImGui_begin_cb,
	beginEx: basis_odin_ImGui_beginEx_cb,
	end: basis_odin_ImGui_end_cb,
	beginMenu: basis_odin_ImGui_beginMenu_cb,
	endMenu: basis_odin_ImGui_endMenu_cb,
	menuItem: basis_odin_ImGui_menuItem_cb,
	openPopup: basis_odin_ImGui_openPopup_cb,
	beginPopup: basis_odin_ImGui_beginPopup_cb,
	endPopup: basis_odin_ImGui_endPopup_cb,
	pushStyleColor: basis_odin_ImGui_pushStyleColor_cb,
	popStyleColor: basis_odin_ImGui_popStyleColor_cb,
	separator: basis_odin_ImGui_separator_cb,
	text: basis_odin_ImGui_text_cb,
	textColored: basis_odin_ImGui_textColored_cb,
	sameline: basis_odin_ImGui_sameline_cb,
	collapsingHeader: basis_odin_ImGui_collapsingHeader_cb,
	button: basis_odin_ImGui_button_cb,
	isItemHovered: basis_odin_ImGui_isItemHovered_cb,
	setTooltip: basis_odin_ImGui_setTooltip_cb,
	endTooltip: basis_odin_ImGui_endTooltip_cb,
	setNextWindowPos: basis_odin_ImGui_setNextWindowPos_cb,
	setNextWindowSize: basis_odin_ImGui_setNextWindowSize_cb,
	setNextWindowBgAlpha: basis_odin_ImGui_setNextWindowBgAlpha_cb,
	beginListBox: basis_odin_ImGui_beginListBox_cb,
	endListBox: basis_odin_ImGui_endListBox_cb,
	radioButton: basis_odin_ImGui_radioButton_cb,
	getScrollX: basis_odin_ImGui_getScrollX_cb,
	getScrollY: basis_odin_ImGui_getScrollY_cb,
	setScrollX: basis_odin_ImGui_setScrollX_cb,
	setScrollY: basis_odin_ImGui_setScrollY_cb,
	getScrollMaxX: basis_odin_ImGui_getScrollMaxX_cb,
	getScrollMaxY: basis_odin_ImGui_getScrollMaxY_cb,
	setScrollHereX: basis_odin_ImGui_setScrollHereX_cb,
	setScrollHereY: basis_odin_ImGui_setScrollHereY_cb,
	setScrollFromPosX: basis_odin_ImGui_setScrollFromPosX_cb,
	setScrollFromPosY: basis_odin_ImGui_setScrollFromPosY_cb,
	dragFloat: basis_odin_ImGui_dragFloat_cb,
	dragInt: basis_odin_ImGui_dragInt_cb,
	sliderFloat: basis_odin_ImGui_sliderFloat_cb,
	sliderInt: basis_odin_ImGui_sliderInt_cb,
) {
	_ImGui_begin = begin
	_ImGui_beginEx = beginEx
	_ImGui_end = end
	_ImGui_beginMenu = beginMenu
	_ImGui_endMenu = endMenu
	_ImGui_menuItem = menuItem
	_ImGui_openPopup = openPopup
	_ImGui_beginPopup = beginPopup
	_ImGui_endPopup = endPopup
	_ImGui_pushStyleColor = pushStyleColor
	_ImGui_popStyleColor = popStyleColor
	_ImGui_separator = separator
	_ImGui_text = text
	_ImGui_textColored = textColored
	_ImGui_sameline = sameline
	_ImGui_collapsingHeader = collapsingHeader
	_ImGui_button = button
	_ImGui_isItemHovered = isItemHovered
	_ImGui_setTooltip = setTooltip
	_ImGui_endTooltip = endTooltip
	_ImGui_setNextWindowPos = setNextWindowPos
	_ImGui_setNextWindowSize = setNextWindowSize
	_ImGui_setNextWindowBgAlpha = setNextWindowBgAlpha
	_ImGui_beginListBox = beginListBox
	_ImGui_endListBox = endListBox
	_ImGui_radioButton = radioButton
	_ImGui_getScrollX = getScrollX
	_ImGui_getScrollY = getScrollY
	_ImGui_setScrollX = setScrollX
	_ImGui_setScrollY = setScrollY
	_ImGui_getScrollMaxX = getScrollMaxX
	_ImGui_getScrollMaxY = getScrollMaxY
	_ImGui_setScrollHereX = setScrollHereX
	_ImGui_setScrollHereY = setScrollHereY
	_ImGui_setScrollFromPosX = setScrollFromPosX
	_ImGui_setScrollFromPosY = setScrollFromPosY
	_ImGui_dragFloat = dragFloat
	_ImGui_dragInt = dragInt
	_ImGui_sliderFloat = sliderFloat
	_ImGui_sliderInt = sliderInt
}

// ===============================

// class GameObjectCreationParameters

@export
bindGameObjectCreationParameters :: proc "c" (
	newParams: basis_odin_GameObjectCreationParameters_newParams_cb,
	newParamsWithNameAndType: basis_odin_GameObjectCreationParameters_newParamsWithNameAndType_cb,
	deleteParams: basis_odin_GameObjectCreationParameters_deleteParams_cb,
	setStartTransform: basis_odin_GameObjectCreationParameters_setStartTransform_cb,
	setPropertyBundlePath: basis_odin_GameObjectCreationParameters_setPropertyBundlePath_cb,
) {
	_GameObjectCreationParameters_newParams = newParams
	_GameObjectCreationParameters_newParamsWithNameAndType = newParamsWithNameAndType
	_GameObjectCreationParameters_deleteParams = deleteParams
	_GameObjectCreationParameters_setStartTransform = setStartTransform
	_GameObjectCreationParameters_setPropertyBundlePath = setPropertyBundlePath
}

// ===============================

// class OSUtility

@export
bindOSUtility :: proc "c" (
	writeStringToClipboard: basis_odin_OSUtility_writeStringToClipboard_cb,
) {
	_OSUtility_writeStringToClipboard = writeStringToClipboard
}

// ===============================

// class ExposedPropertyLayoutReader

@export
bindExposedPropertyLayoutReader :: proc "c" (
	init: basis_odin_ExposedPropertyLayoutReader_init_cb,
	processProperty: basis_odin_ExposedPropertyLayoutReader_processProperty_cb,
	processString: basis_odin_ExposedPropertyLayoutReader_processString_cb,
	processResourceRef: basis_odin_ExposedPropertyLayoutReader_processResourceRef_cb,
	processButton: basis_odin_ExposedPropertyLayoutReader_processButton_cb,
	processCategory: basis_odin_ExposedPropertyLayoutReader_processCategory_cb,
	processEnum: basis_odin_ExposedPropertyLayoutReader_processEnum_cb,
	allPropertiesProcessed: basis_odin_ExposedPropertyLayoutReader_allPropertiesProcessed_cb,
) {
	_ExposedPropertyLayoutReader_init = init
	_ExposedPropertyLayoutReader_processProperty = processProperty
	_ExposedPropertyLayoutReader_processString = processString
	_ExposedPropertyLayoutReader_processResourceRef = processResourceRef
	_ExposedPropertyLayoutReader_processButton = processButton
	_ExposedPropertyLayoutReader_processCategory = processCategory
	_ExposedPropertyLayoutReader_processEnum = processEnum
	_ExposedPropertyLayoutReader_allPropertiesProcessed = allPropertiesProcessed
}

// ===============================

// class ZigAngelScriptTypeRegistration

@export
bindZigAngelScriptTypeRegistration :: proc "c" (
	registerEnumType: basis_odin_ZigAngelScriptTypeRegistration_registerEnumType_cb,
	registerEnumValue: basis_odin_ZigAngelScriptTypeRegistration_registerEnumValue_cb,
) {
	_ZigAngelScriptTypeRegistration_registerEnumType = registerEnumType
	_ZigAngelScriptTypeRegistration_registerEnumValue = registerEnumValue
}

// ===============================

// class ZigAngelScriptComponentRegistration

@export
bindZigAngelScriptComponentRegistration :: proc "c" (
	registerComponentType: basis_odin_ZigAngelScriptComponentRegistration_registerComponentType_cb,
	registerComponentMethod: basis_odin_ZigAngelScriptComponentRegistration_registerComponentMethod_cb,
	registerComponentEventAutoComplete: basis_odin_ZigAngelScriptComponentRegistration_registerComponentEventAutoComplete_cb,
) {
	_ZigAngelScriptComponentRegistration_registerComponentType = registerComponentType
	_ZigAngelScriptComponentRegistration_registerComponentMethod = registerComponentMethod
	_ZigAngelScriptComponentRegistration_registerComponentEventAutoComplete = registerComponentEventAutoComplete
}

// ===============================

// class AngelScriptUtils

@export
bindAngelScriptUtils :: proc "c" (
	getStringRefConstIn: basis_odin_AngelScriptUtils_getStringRefConstIn_cb,
	setStringRefOut: basis_odin_AngelScriptUtils_setStringRefOut_cb,
	getGameObjectRefConstIn: basis_odin_AngelScriptUtils_getGameObjectRefConstIn_cb,
	getHashFromGameObjectRefConstIn: basis_odin_AngelScriptUtils_getHashFromGameObjectRefConstIn_cb,
	setGameObjectRefOut: basis_odin_AngelScriptUtils_setGameObjectRefOut_cb,
	getColorRefConstIn: basis_odin_AngelScriptUtils_getColorRefConstIn_cb,
	setColorRefOut: basis_odin_AngelScriptUtils_setColorRefOut_cb,
	addRefToASFuncPtr: basis_odin_AngelScriptUtils_addRefToASFuncPtr_cb,
	releaseASFuncPtr: basis_odin_AngelScriptUtils_releaseASFuncPtr_cb,
) {
	_AngelScriptUtils_getStringRefConstIn = getStringRefConstIn
	_AngelScriptUtils_setStringRefOut = setStringRefOut
	_AngelScriptUtils_getGameObjectRefConstIn = getGameObjectRefConstIn
	_AngelScriptUtils_getHashFromGameObjectRefConstIn = getHashFromGameObjectRefConstIn
	_AngelScriptUtils_setGameObjectRefOut = setGameObjectRefOut
	_AngelScriptUtils_getColorRefConstIn = getColorRefConstIn
	_AngelScriptUtils_setColorRefOut = setColorRefOut
	_AngelScriptUtils_addRefToASFuncPtr = addRefToASFuncPtr
	_AngelScriptUtils_releaseASFuncPtr = releaseASFuncPtr
}

// ===============================

